name: down
on:
  schedule:
    # At 06:00, 09:00 (KST 15:00, 18:00) on every day-of-week from Monday through Friday
    # - cron: "0 6 * * 1-5"
    # - cron: "0 9 * * 1-5"

jobs:
  down:
    runs-on: [self-hosted, cmbp-16]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          npm i -g deskctl
          deskctl 15 -t %
      - id: current
        run:
          echo "::set-output name=DESK_VALUE::$(deskctl -s -t %)"
      - run: |
          curl -X "PATCH" "https://api.github.com/repos/chitacan/deskctl/issues/1" \
               -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               -H 'Content-Type: application/json; charset=utf-8' \
               -d $'{
            "body": "```\\n{\\n  \\"height\\": \\"${{ steps.current.outputs.DESK_VALUE }}\\"\\n}\\n```"
          }'
