name: move
on:
  workflow_dispatch:
    inputs:
      value:
        description: "value to move"
        required: true
      type:
        description: "type of value (cm, %, raw)"
        required: true
        default: "%"

jobs:
  move:
    runs-on: [self-hosted, cmbp-16]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          npm i -g deskctl
          deskctl ${{ github.event.inputs.value }} -t ${{ github.event.inputs.type }}
      - id: current
        run:
          echo "::set-output name=DESK_VALUE::$(deskctl -s -t %)"
      - run: |
          curl -X "PATCH" "https://api.github.com/repos/chitacan/deskctl/issues/1" \
               -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               -H 'Content-Type: application/json; charset=utf-8' \
               -d $'{
            "body": "```\\n{\\n  \\"height\\": \\"${{ steps.current.outputs.DESK_VALUE }}\\"\\n}\\n```"
          }'
